In [1]:
import numpy as np
import pandas as pd 
from googletrans import Translator

In [2]:
path = 'perpusnas_google_review-2023_01_27_17_57_20.csv'
df = pd.read_csv(path)

In [3]:
df

,id,nama,rating,review,waktu
0,ChdDSUhNMG9nS0VJQ0FnSURCdzh2RC1BRRAB,sulistiawati 74,5 bintang,Sangat edukatif buat anak-anak agar cinta ilmu...,2 jam lalu
1,ChdDSUhNMG9nS0VJQ0FnSURCdy1iNmxRRRAB,Syahidah Izzati,5 bintang,Nyaman banget tempatnya ❣️,4 jam lalu
2,ChZDSUhNMG9nS0VJQ0FnSURCdzR6d0pREAE,Sierra,5 bintang,"nyaman, luas, bersih",5 jam lalu
3,ChZDSUhNMG9nS0VJQ0FnSURCZzdYVlVBEAE,Erwin rachman,5 bintang,NaN,7 jam lalu
4,ChZDSUhNMG9nS0VJQ0FnSURCX2FQTmJnEAE,Nathaniel Bonardo,5 bintang,NaN,12 jam lalu
...,...,...,...,...,...
365,ChdDSUhNMG9nS0VJQ0FnSUQtaW96dHBBRRAB,NASRUDDIN ASN,5 bintang,NaN,2 bulan lalu
366,ChdDSUhNMG9nS0VJQ0FnSUQtaXZUczlRRRAB,Abrid Madilantoro,5 bintang,bisa lihat monas,2 bulan lalu
367,ChZDSUhNMG9nS0VJQ0FnSUQtOHA3cWFnEAE,Azizah Syifa Saniyyah,5 bintang,NaN,2 bulan lalu
368,ChdDSUhNMG9nS0VJQ0FnSUQtOHV5VWxRRRAB,Fenton Martin,5 bintang,NaN,2 bulan lalu
369,ChdDSUhNMG9nS0VJQ0FnSUQta3NId3h3RRAB,Nur Aisyah Syabandiah,4 bintang,NaN,2 bulan lalu

In [11]:
reviews = df[df['review'].notnull()][:-2].reset_index()

In [12]:
reviews

,index,id,nama,rating,review,waktu
0,0,ChdDSUhNMG9nS0VJQ0FnSURCdzh2RC1BRRAB,sulistiawati 74,5 bintang,Sangat edukatif buat anak-anak agar cinta ilmu...,2 jam lalu
1,1,ChdDSUhNMG9nS0VJQ0FnSURCdy1iNmxRRRAB,Syahidah Izzati,5 bintang,Nyaman banget tempatnya ❣️,4 jam lalu
2,2,ChZDSUhNMG9nS0VJQ0FnSURCdzR6d0pREAE,Sierra,5 bintang,"nyaman, luas, bersih",5 jam lalu
3,5,ChdDSUhNMG9nS0VJQ0FnSURCX2ZiOXhRRRAB,Titut Festyanto,5 bintang,That was a good place to get many ways of info...,14 jam lalu
4,6,ChZDSUhNMG9nS0VJQ0FnSURCOWJibFJBEAE,abel Abraham,5 bintang,Bagus tempat oke buat belajar atau buat baca b...,2 hari lalu
...,...,...,...,...,...,...
165,353,ChdDSUhNMG9nS0VJQ0FnSUQtMXYyUzNBRRAB,Ishak ID,5 bintang,Perpustakaan dengan fasilitas yang sangat baik...,sebulan lalu
166,354,ChZDSUhNMG9nS0VJQ0FnSUQtbHJfdkxBEAE,Irpan Batubara,5 bintang,Lokasinya di dekat Monas. Siapa saja boleh ke ...,sebulan lalu
167,355,ChZDSUhNMG9nS0VJQ0FnSUQtNXV6a0JREAE,Amruta Sharma,5 bintang,Very nice and comfortable place to read\n\n(Di...,sebulan lalu
168,357,ChdDSUhNMG9nS0VJQ0FnSURVelk3RjZnRRAB,Ros FY,5 bintang,"Jangan lupa mampir ke perpusnas, dr lt. 24 k...",sebulan lalu
169,360,ChZDSUhNMG9nS0VJQ0FnSUQtMnJXck5BEAE,Debora Anggiarini,4 bintang,Bagus dan bersih,sebulan lalu

In [13]:
#create our translator object 
translator = Translator()

reviews['en_review'] = reviews['review'].apply(lambda x: translator.translate(x, src='auto', dest='en').text)

In [14]:
reviews

,index,id,nama,rating,review,waktu,en_review
0,0,ChdDSUhNMG9nS0VJQ0FnSURCdzh2RC1BRRAB,sulistiawati 74,5 bintang,Sangat edukatif buat anak-anak agar cinta ilmu...,2 jam lalu,Very educative for children to love science an...
1,1,ChdDSUhNMG9nS0VJQ0FnSURCdy1iNmxRRRAB,Syahidah Izzati,5 bintang,Nyaman banget tempatnya ❣️,4 jam lalu,Very comfortable place ❣️
2,2,ChZDSUhNMG9nS0VJQ0FnSURCdzR6d0pREAE,Sierra,5 bintang,"nyaman, luas, bersih",5 jam lalu,"comfortable, spacious, clean"
3,5,ChdDSUhNMG9nS0VJQ0FnSURCX2ZiOXhRRRAB,Titut Festyanto,5 bintang,That was a good place to get many ways of info...,14 jam lalu,That was a good place to get many ways of info...
4,6,ChZDSUhNMG9nS0VJQ0FnSURCOWJibFJBEAE,abel Abraham,5 bintang,Bagus tempat oke buat belajar atau buat baca b...,2 hari lalu,Good place okay for learning or to read readin...
...,...,...,...,...,...,...,...
165,353,ChdDSUhNMG9nS0VJQ0FnSUQtMXYyUzNBRRAB,Ishak ID,5 bintang,Perpustakaan dengan fasilitas yang sangat baik...,sebulan lalu,Library with excellent facilities.The National...
166,354,ChZDSUhNMG9nS0VJQ0FnSUQtbHJfdkxBEAE,Irpan Batubara,5 bintang,Lokasinya di dekat Monas. Siapa saja boleh ke ...,sebulan lalu,The location is near Monas.Anyone can go there...
167,355,ChZDSUhNMG9nS0VJQ0FnSUQtNXV6a0JREAE,Amruta Sharma,5 bintang,Very nice and comfortable place to read\n\n(Di...,sebulan lalu,Very nice and comfortable place to read\n\n(Tr...
168,357,ChdDSUhNMG9nS0VJQ0FnSURVelk3RjZnRRAB,Ros FY,5 bintang,"Jangan lupa mampir ke perpusnas, dr lt. 24 k...",sebulan lalu,"Don't forget to stop by the National Library, ..."
169,360,ChZDSUhNMG9nS0VJQ0FnSUQtMnJXck5BEAE,Debora Anggiarini,4 bintang,Bagus dan bersih,sebulan lalu,Good and clean